"""segments 表：影片片段（字幕／畫面描述／OCR／embedding）的 schema 與 CRUD。"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

import psycopg

from . import get_connection


@dataclass(frozen=True)
class ModalityFlags:
    """某支影片「有沒有這個模態的內容」——`schemas/videos.py` 的 VideoOut 用來
    填 has_transcript／has_visual／has_ocr。預設全 False，對應「這支影片還沒有
    任何片段」（例如 pending 影片）。
    """
    has_transcript: bool = False
    has_visual: bool = False
    has_ocr: bool = False


@dataclass
class SegmentRecord:
    id: int
    video_id: int
    start_sec: float
    end_sec: float
    transcript: str | None
    visual_description: str | None
    ocr_text: str | None
    transcript_embedding: bytes | None
    visual_embedding: bytes | None
    ocr_embedding: bytes | None
    asr_model: str | None
    vlm_model: str | None
    embedding_model: str | None
    created_at: str
    no_speech_prob: float | None
    avg_logprob: float | None
    compression_ratio: float | None
    vlm_frame_count: int | None


def create_table(conn: psycopg.Connection) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS segments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            video_id INTEGER NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
            start_sec DOUBLE PRECISION NOT NULL,
            end_sec DOUBLE PRECISION NOT NULL,
            transcript TEXT,
            visual_description TEXT,
            ocr_text TEXT,
            transcript_embedding BYTEA,
            visual_embedding BYTEA,
            ocr_embedding BYTEA,
            asr_model TEXT,
            vlm_model TEXT,
            embedding_model TEXT,
            no_speech_prob DOUBLE PRECISION,
            avg_logprob DOUBLE PRECISION,
            compression_ratio DOUBLE PRECISION,
            -- 這個片段的畫面描述用了幾張畫面產生，見 pipeline/analyzer/phases.py 的
            -- FRAME_FRACTIONS（現在一律三幀；曾經有過單幀／條件式多幀）；NULL 代表這筆
            -- 資料是欄位新增前的舊資料，語意上等同單幀（當時只有單幀取樣）。
            vlm_frame_count INTEGER,
            created_at TEXT NOT NULL,
            -- 關鍵字檢索的比對來源。SQLite 時期這是一張獨立的 FTS5 虛擬表
            -- （segments_fts），rowid 靠呼叫端自己跟 segments.id 同步；改成
            -- generated column 之後由資料庫自己維護，插入／刪除／更新都不可能
            -- 再漏掉，見下面 GIN 索引的說明。
            content TEXT GENERATED ALWAYS AS (
                COALESCE(transcript, '') || ' ' || COALESCE(visual_description, '') || ' ' || COALESCE(ocr_text, '')
            ) STORED
        )
        """
    )
    conn.execute("CREATE INDEX IF NOT EXISTS idx_segments_video_id ON segments(video_id)")
    # 中文關鍵字檢索索引，見 docs/02-technical-decisions.md#搜尋 與
    # docs/14-postgresql-migration-plan.md §5。
    #
    # 為什麼是 trigram 而不是 PostgreSQL 內建的 to_tsvector 全文檢索：中文沒有
    # 空白斷詞，tsvector 的 'simple' parser 會把整句當成一個 token，子字串完全
    # 比對不到；要正確斷中文詞得裝 zhparser／pgroonga 這類額外 extension。
    # trigram 不需要斷詞就能比對中文子字串，跟 SQLite 時期選 tokenize='trigram'
    # 是同一個理由，遷移前後的檢索語意因此保持一致。
    #
    # 索引只在 pattern 有 3 個以上連續字元時才吃得到（要抽得出完整 trigram）；
    # 2 字元的詞仍然查得到，只是走 seq scan——這點跟 SQLite FTS5「<3 字元完全
    # 查不到」不同，見 docs/14 §5.2.1，那個差異刻意沒有拿來改搜尋行為。
    conn.execute(
        "CREATE INDEX IF NOT EXISTS idx_segments_content_trgm ON segments USING gin (content gin_trgm_ops)"
    )


def delete_for_video(conn: psycopg.Connection, video_id: int) -> None:
    """刪掉一支影片的所有片段。

    收 conn 而不是自己開連線：呼叫端（reset_to_pending／delete_video／
    clear_analysis_output）都要把它跟 videos 表的更新綁在同一個交易裡。

    SQLite 時期這裡還要多一句「連 segments_fts 的對應列一起刪」，因為那張
    FTS5 表的 rowid 是靠呼叫端自己同步的，只 DELETE segments 會留下一堆對不到
    片段的殘留列——而 fts_bm25_search() 是「先取 bm25 前 200 名、再由 sparse.py
    過濾掉不存在的 id」，殘留列會佔掉那 200 個名額，把真正命中的片段擠出候選集
    （實測一支用了一陣子的 app.db 有 925/1795、52% 是殘留列）。
    改成 generated column 之後 content 隨著這一句 DELETE 一起消失，這整類問題
    在結構上就不存在了。
    """
    conn.execute("DELETE FROM segments WHERE video_id = %s", (video_id,))


def insert_segment(
    video_id: int,
    start_sec: float,
    end_sec: float,
    transcript: str | None,
    visual_description: str | None,
    ocr_text: str | None,
    transcript_embedding: bytes | None,
    visual_embedding: bytes | None,
    asr_model: str | None,
    vlm_model: str | None,
    embedding_model: str | None,
    ocr_embedding: bytes | None = None,
    no_speech_prob: float | None = None,
    avg_logprob: float | None = None,
    compression_ratio: float | None = None,
    vlm_frame_count: int | None = None,
) -> int:
    created_at = datetime.now().isoformat(timespec="seconds")
    with get_connection() as conn:
        cursor = conn.execute(
            """
            INSERT INTO segments (
                video_id, start_sec, end_sec, transcript, visual_description, ocr_text,
                transcript_embedding, visual_embedding, ocr_embedding, asr_model, vlm_model,
                embedding_model, no_speech_prob, avg_logprob, compression_ratio, vlm_frame_count, created_at
            ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (
                video_id,
                start_sec,
                end_sec,
                transcript,
                visual_description,
                ocr_text,
                transcript_embedding,
                visual_embedding,
                ocr_embedding,
                asr_model,
                vlm_model,
                embedding_model,
                no_speech_prob,
                avg_logprob,
                compression_ratio,
                vlm_frame_count,
                created_at,
            ),
        )
        return cursor.fetchone()["id"]


def list_segments_for_video(video_id: int) -> list[SegmentRecord]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM segments WHERE video_id = %s ORDER BY start_sec", (video_id,)
        ).fetchall()
        return [_row_to_segment(row) for row in rows]


def list_segments_for_videos(video_ids: list[int]) -> list[SegmentRecord]:
    """限定在數支影片內的片段，給搜尋的多選範圍用（單支影片走
    list_segments_for_video()，那個還有 analyzer／video_service 等呼叫端）。
    空 list 代表「沒有任何影片可搜」而不是「全部」——直接回空，不要讓
    `= ANY('{}')` 靜靜地掃出零筆，語意上比較清楚。
    """
    if not video_ids:
        return []
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM segments WHERE video_id = ANY(%s) ORDER BY video_id, start_sec",
            (list(video_ids),),
        ).fetchall()
        return [_row_to_segment(row) for row in rows]


def list_all_segments() -> list[SegmentRecord]:
    with get_connection() as conn:
        rows = conn.execute("SELECT * FROM segments ORDER BY video_id, start_sec").fetchall()
        return [_row_to_segment(row) for row in rows]


def modality_flags_by_video(video_ids: list[int] | None = None) -> dict[int, ModalityFlags]:
    """每支影片各有哪些模態的內容，一次聚合查詢算完。傳 video_ids 就只算那幾支，
    None 代表全部。沒有任何片段的影片不會出現在回傳的 dict 裡，呼叫端用
    `.get(video_id, ModalityFlags())` 取值即可。

    刻意不走「載入 SegmentRecord 再用 any() 判斷」：那個做法會把每個片段的三個
    embedding BLOB 也一起讀出來（實測 10 支影片／746 個片段約 4.5MB、47ms），
    只為了算三個布林值。`COALESCE(col, '') <> ''` 對應原本 `any(s.transcript
    for s in segments)` 的 Python truthiness——NULL 與空字串都不算有內容。

    聚合函式用 bool_or() 而不是 SQLite 時期的 MAX()：SQLite 沒有布林型別、
    比較結果是 0/1 整數，MAX() 剛好能拿來當「有沒有任何一列成立」；PostgreSQL
    的比較結果是真正的 boolean，MAX(boolean) 沒有定義、會直接報錯。
    """
    where = ""
    params: list[object] = []
    if video_ids is not None:
        if not video_ids:
            return {}
        # `= ANY(%s)` 直接吃一個 list，不用像 SQLite 那樣按長度動態拼佔位符。
        where = " WHERE video_id = ANY(%s)"
        params = [list(video_ids)]

    with get_connection() as conn:
        rows = conn.execute(
            f"""
            SELECT video_id,
                   bool_or(COALESCE(transcript, '') <> '') AS has_transcript,
                   bool_or(COALESCE(visual_description, '') <> '') AS has_visual,
                   bool_or(COALESCE(ocr_text, '') <> '') AS has_ocr
            FROM segments{where}
            GROUP BY video_id
            """,
            params,
        ).fetchall()

    return {
        row["video_id"]: ModalityFlags(
            has_transcript=bool(row["has_transcript"]),
            has_visual=bool(row["has_visual"]),
            has_ocr=bool(row["has_ocr"]),
        )
        for row in rows
    }


# BM25 的兩個標準參數，跟 SQLite FTS5 的 bm25() 預設值一致（k1=1.2、b=0.75），
# 讓遷移前後的加權行為盡量對齊。k1 控制詞頻飽和速度、b 控制文件長度正規化強度。
_BM25_K1 = 1.2
_BM25_B = 0.75

# 自己算 BM25，取代 SQLite 內建的 bm25()。PostgreSQL 沒有等價的內建函式
# （ts_rank 只做 tsvector，對中文不能用，見 create_table 的說明），所以直接
# 用 SQL 把公式寫出來。930 個片段的規模下這個查詢是毫秒級。
#
# 為什麼一定要保住 IDF：sparse.py 整套短詞比例門檻邏輯建立在「長詞有真實
# IDF 加權」的前提上——實測「全壘打」只命中 10 個片段、「畫面」命中 527 個，
# 沒有 IDF 的話兩者會被同等對待，排序整個跑掉。
#
# 分數加負號：呼叫端（sparse.py／fusion.py）沿用 SQLite bm25() 的慣例，
# 數字越小（越負）代表越相關，這個介面契約不變。
#
# scope CTE 是搜尋範圍（`video_ids` 為 NULL 就是全庫，語意跟加這層之前逐字
# 相同）。範圍一定要在這裡下推、不能只靠呼叫端事後過濾：`LIMIT` 是在**排序
# 之後**才截斷的，範圍外的片段會先把前 200 個名額佔走，限定範圍搜尋時
# sparse channel 就整個落空（同一個「名額被佔走」的失敗模式，SQLite 時期
# 的殘留列已經踩過一次，見 create_table 的說明）。
#
# 兩個容易寫錯的點：
#   1. `NOT MATERIALIZED` 不可省略。scope 被 df／hits 引用兩次，PostgreSQL
#      預設會物化它，content 上的 pg_trgm GIN 索引就吃不到了；加了提示才會
#      inline 回原表、保住索引。
#   2. stats 也要讀 scope，不能只縮 df／hits。IDF 的分母（n_docs）與長度
#      正規化（avg_len）必須跟 n_hits 算在同一份語料上，否則限定範圍時
#      IDF 會被全庫的文件數灌水。
_BM25_SQL = f"""
WITH scope AS NOT MATERIALIZED (
    SELECT id, content
    FROM segments
    WHERE %(video_ids)s::int[] IS NULL OR video_id = ANY(%(video_ids)s::int[])
),
stats AS (
    SELECT count(*)::float8 AS n_docs,
           GREATEST(COALESCE(avg(length(content)), 1), 1)::float8 AS avg_len
    FROM scope
),
q AS (
    SELECT term, pattern FROM unnest(%(terms)s::text[], %(patterns)s::text[]) AS t(term, pattern)
),
df AS (
    -- 每個詞命中幾個片段（document frequency），IDF 的分母
    SELECT q.term, q.pattern, count(s.id)::float8 AS n_hits
    FROM q LEFT JOIN scope s ON s.content ILIKE q.pattern
    GROUP BY q.term, q.pattern
),
hits AS (
    SELECT s.id,
           df.n_hits,
           length(s.content)::float8 AS doc_len,
           -- 詞頻：用「把該詞全部抽掉之後少了幾個字元」除以詞長回推出現次數
           (length(s.content) - length(replace(lower(s.content), lower(df.term), '')))::float8
               / GREATEST(length(df.term), 1) AS tf
    FROM df JOIN scope s ON s.content ILIKE df.pattern
    WHERE df.n_hits > 0
)
SELECT h.id,
       -SUM(
           ln(1.0 + (stats.n_docs - h.n_hits + 0.5) / (h.n_hits + 0.5))
           * (h.tf * ({_BM25_K1} + 1.0))
           / (h.tf + {_BM25_K1} * (1.0 - {_BM25_B} + {_BM25_B} * h.doc_len / stats.avg_len))
       ) AS score
FROM hits h CROSS JOIN stats
GROUP BY h.id
ORDER BY score
LIMIT %(limit)s
"""


def _like_escape(term: str) -> str:
    """把 LIKE 的萬用字元跳脫掉，讓使用者輸入的 % 或 _ 當成普通字元比對。
    `extract_terms()` 不會主動產生這些字元，但使用者直接打進查詢字串就會
    留下來，沒跳脫的話 `%` 會變成「比對任意字串」。
    """
    return term.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")


def fts_bm25_search(
    terms: list[str], limit: int = 200, video_ids: list[int] | None = None
) -> list[tuple[int, float]]:
    """對關鍵字做 OR 檢索，回傳 (segment_id, BM25 分數)——數字越小（越負）
    代表越相關，跟 SQLite 時期的 bm25() 慣例相同。

    video_ids 是搜尋範圍：None 代表全庫，給一組 id 就只在那幾支影片內排名與
    截斷（理由見 _BM25_SQL 上方的說明——LIMIT 在排序之後才套用，範圍不下推
    的話名額會被範圍外的片段佔走）。空 list 代表「沒有影片可搜」，直接回空。

    呼叫端（sparse.py）只送 >=3 字元的詞進來。那個限制在 SQLite 是硬性的
    （trigram tokenizer 對更短的詞產不出 token、完全查不到），在 PostgreSQL
    只影響能不能吃到 GIN 索引——更短的詞一樣查得到，只是走 seq scan。
    這個差異刻意沒有拿來改搜尋行為，見 docs/14-postgresql-migration-plan.md §5.2.1。
    """
    if not terms:
        return []
    if video_ids is not None and not video_ids:
        return []
    patterns = [f"%{_like_escape(t)}%" for t in terms]
    params = {
        "terms": list(terms),
        "patterns": patterns,
        "limit": limit,
        "video_ids": list(video_ids) if video_ids is not None else None,
    }
    with get_connection() as conn:
        rows = conn.execute(_BM25_SQL, params).fetchall()
    return [(row["id"], row["score"]) for row in rows]


def fts_like_search(term: str, limit: int = 200, video_ids: list[int] | None = None) -> list[int]:
    """給 <3 字元的關鍵字用的 fallback：純子字串比對，回傳 segment_id 列表，
    沒有分數。video_ids 的語意跟 fts_bm25_search() 相同（同樣有 LIMIT 名額被
    範圍外片段佔走的問題，所以範圍一樣要下推到 SQL）。

    多了 ORDER BY id：PostgreSQL 的 LIMIT 沒有 ORDER BY 時回傳哪幾列是不保證的，
    而呼叫端會拿這個結果去算比例門檻，需要每次執行結果一致才好推理。
    """
    if video_ids is not None and not video_ids:
        return []
    with get_connection() as conn:
        rows = conn.execute(
            """
            SELECT id FROM segments
            WHERE content ILIKE %(pattern)s
              AND (%(video_ids)s::int[] IS NULL OR video_id = ANY(%(video_ids)s::int[]))
            ORDER BY id LIMIT %(limit)s
            """,
            {
                "pattern": f"%{_like_escape(term)}%",
                "limit": limit,
                "video_ids": list(video_ids) if video_ids is not None else None,
            },
        ).fetchall()
    return [row["id"] for row in rows]


def _row_to_segment(row: dict) -> SegmentRecord:
    """SQLite 時期這裡對後加的四個欄位是寫成 `row["x"] if "x" in keys else None`
    ——因為 migrate_columns() 之前建立的舊資料庫真的可能沒有那些欄位。
    PostgreSQL 的 schema 由 create_table() 一次定義齊全，不存在「缺欄位的舊
    資料庫」，所以一律直接取值。
    """
    return SegmentRecord(
        id=row["id"],
        video_id=row["video_id"],
        start_sec=row["start_sec"],
        end_sec=row["end_sec"],
        transcript=row["transcript"],
        visual_description=row["visual_description"],
        ocr_text=row["ocr_text"],
        transcript_embedding=row["transcript_embedding"],
        visual_embedding=row["visual_embedding"],
        ocr_embedding=row["ocr_embedding"],
        asr_model=row["asr_model"],
        vlm_model=row["vlm_model"],
        embedding_model=row["embedding_model"],
        created_at=row["created_at"],
        no_speech_prob=row["no_speech_prob"],
        avg_logprob=row["avg_logprob"],
        compression_ratio=row["compression_ratio"],
        vlm_frame_count=row["vlm_frame_count"],
    )
