"""videos 表：影片主表的 schema 與 CRUD。"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime

import psycopg

from . import get_connection, segments

STATUS_PENDING = "pending"
STATUS_ANALYZING = "analyzing"
STATUS_ANALYZED = "analyzed"
STATUS_FAILED = "failed"

SOURCE_YOUTUBE = "youtube"
SOURCE_LOCAL = "local"


@dataclass
class VideoRecord:
    id: int
    title: str
    source: str
    source_url: str | None
    file_path: str
    duration_sec: int | None
    status: str
    pipeline_stage: str | None
    created_at: str
    analyzed_at: str | None
    segment_count: int | None
    cost_usd: float | None
    asr_model: str | None
    vlm_model: str | None
    embedding_model: str | None
    summary: str | None
    summary_model: str | None


@dataclass
class HeaderStatsData:
    pending_count: int
    analyzed_count: int
    segment_count: int
    total_cost_usd: float


def create_table(conn: psycopg.Connection) -> None:
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS videos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            source TEXT NOT NULL,
            source_url TEXT,
            file_path TEXT NOT NULL,
            duration_sec INTEGER,
            status TEXT NOT NULL DEFAULT 'pending',
            pipeline_stage TEXT,
            created_at TEXT NOT NULL,
            analyzed_at TEXT,
            segment_count INTEGER,
            cost_usd DOUBLE PRECISION,
            -- 以下五欄在 SQLite 時期是靠 migrate_columns() 對既有資料庫後補的；
            -- PostgreSQL 是全新資料庫，一次定義齊全，那個機制連同
            -- _VIDEOS_NEW_COLUMNS 一起移除了。
            asr_model TEXT,
            vlm_model TEXT,
            embedding_model TEXT,
            summary TEXT,
            summary_model TEXT
        )
        """
    )


def insert_video(
    title: str,
    source: str,
    source_url: str | None,
    file_path: str,
    duration_sec: int | None,
) -> int:
    created_at = datetime.now().isoformat(timespec="seconds")
    with get_connection() as conn:
        cursor = conn.execute(
            """
            INSERT INTO videos (title, source, source_url, file_path, duration_sec, status, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            RETURNING id
            """,
            (title, source, source_url, file_path, duration_sec, STATUS_PENDING, created_at),
        )
        return cursor.fetchone()["id"]


def get_video(video_id: int) -> VideoRecord | None:
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM videos WHERE id = %s", (video_id,)).fetchone()
        return _row_to_record(row) if row else None


def find_by_source_url(source_url: str) -> VideoRecord | None:
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM videos WHERE source_url = %s", (source_url,)).fetchone()
        return _row_to_record(row) if row else None


# 一支影片在任何時刻都恰好屬於兩個清單的其中一個。分界是 analyzed_at：
# 有值＝這支影片已經產出過可搜尋的結果，永遠屬於影片庫；沒有值＝還沒產出過，
# 屬於「影片與分析」。status 只決定那一列長什麼樣子，不決定它在哪一頁。
#
# 這條規則是為了讓 analyzing 有地方去。原本的切法是「pending 在工作區、
# analyzed／failed 在影片庫」，中間的 analyzing 兩邊都不收——analyzer 一開始
# 跑就把狀態改成 analyzing，影片會在整段分析期間（實測 43～93 秒）從兩個頁籤
# 同時消失，連那一列上的進度顯示一起帶走。分成兩種 analyzing 之後：
#   第一次分析（analyzed_at IS NULL）→ 留在「影片與分析」原地跑完
#   重新分析（analyzed_at IS NOT NULL）→ 留在「影片庫」原地跑完
_UNANALYZED_WHERE = f"(status = '{STATUS_PENDING}' OR (status = '{STATUS_ANALYZING}' AND analyzed_at IS NULL))"
_LIBRARY_WHERE = (
    f"(status IN ('{STATUS_ANALYZED}', '{STATUS_FAILED}') "
    f"OR (status = '{STATUS_ANALYZING}' AND analyzed_at IS NOT NULL))"
)


def list_unanalyzed_videos() -> list[VideoRecord]:
    """「影片與分析」頁籤用：還沒產出過分析結果的影片（pending＋第一次分析中）。"""
    with get_connection() as conn:
        rows = conn.execute(
            f"SELECT * FROM videos WHERE {_UNANALYZED_WHERE} ORDER BY created_at DESC"
        ).fetchall()
        return [_row_to_record(row) for row in rows]


def get_header_stats() -> HeaderStatsData:
    with get_connection() as conn:
        # 兩個數字各自對齊一個清單，加起來永遠等於影片總數（除了分析失敗的）。
        # 分開算 pending／analyzed 的話，分析中的那段時間裡影片兩邊都不算，
        # Header 的總數會短少一支。
        pending_count = conn.execute(
            f"SELECT COUNT(*) AS c FROM videos WHERE {_UNANALYZED_WHERE}"
        ).fetchone()["c"]
        # 重新分析中的影片一樣算進「已分析」：舊的 segments 還在庫裡、還搜得到，
        # 統計數字要反映資料庫實際有什麼，不是反映有沒有工作在跑。
        row = conn.execute(
            """
            SELECT COUNT(*) AS c, COALESCE(SUM(segment_count), 0) AS s, COALESCE(SUM(cost_usd), 0) AS cost
            FROM videos WHERE analyzed_at IS NOT NULL AND status IN (%s, %s)
            """,
            (STATUS_ANALYZED, STATUS_ANALYZING),
        ).fetchone()
        return HeaderStatsData(
            pending_count=pending_count,
            analyzed_count=row["c"],
            segment_count=row["s"],
            total_cost_usd=row["cost"],
        )


def list_analyzed_videos() -> list[VideoRecord]:
    with get_connection() as conn:
        rows = conn.execute(
            "SELECT * FROM videos WHERE status = %s ORDER BY analyzed_at DESC", (STATUS_ANALYZED,)
        ).fetchall()
        return [_row_to_record(row) for row in rows]


def list_library_videos() -> list[VideoRecord]:
    """「影片庫」頁籤用：分析完成、分析失敗，以及正在重新分析的影片。

    重新分析中的影片留在這裡（不是跳回「影片與分析」再跳回來）：它的舊
    segments 還在、還搜得到，對使用者來說它一直都是庫裡的影片，只是正在
    更新。見 _UNANALYZED_WHERE 上面那段分界說明。
    """
    with get_connection() as conn:
        rows = conn.execute(
            f"SELECT * FROM videos WHERE {_LIBRARY_WHERE} ORDER BY analyzed_at DESC, created_at DESC"
        ).fetchall()
        return [_row_to_record(row) for row in rows]


def update_video_summary(video_id: int, summary: str, summary_model: str, additional_cost_usd: float) -> None:
    """設定摘要並把這次產生摘要的花費累加進 cost_usd（可重複呼叫＝重新產生摘要）。"""
    with get_connection() as conn:
        conn.execute(
            """
            UPDATE videos
            SET summary = %s, summary_model = %s, cost_usd = COALESCE(cost_usd, 0) + %s
            WHERE id = %s
            """,
            (summary, summary_model, additional_cost_usd, video_id),
        )


def clear_analysis_output(video_id: int) -> None:
    """只刪掉既有的 segments 與 ocr_events，videos 表的欄位一個都不動。

    給重新分析用：舊索引要留到新結果真的要寫入的前一刻才換掉（由
    `analyzer._write_segments()` 呼叫），影片在重新分析的整段期間都還搜得到
    舊結果。如果連這個都不做、直接在開始時清空，重新分析就會在那一分鐘裡
    把影片變成一支查不到任何東西的空殼。
    """
    with get_connection() as conn:
        segments.delete_for_video(conn, video_id)
        conn.execute("DELETE FROM ocr_events WHERE video_id = %s", (video_id,))


def reset_to_pending(video_id: int) -> None:
    """把卡住／失敗的分析還原成 pending：清掉部分寫入的 segments、ocr_events 與所有分析欄位。

    segments 的刪除委派給 `segments.delete_for_video()`，ocr_events 則直接
    DELETE——兩者都傳同一個 conn，跟 videos 表的 UPDATE 落在同一個
    get_connection() 交易裡，video 更新失敗時前面的刪除也會一起回滾，維持原子性。
    """
    with get_connection() as conn:
        segments.delete_for_video(conn, video_id)
        conn.execute("DELETE FROM ocr_events WHERE video_id = %s", (video_id,))
        conn.execute(
            """
            UPDATE videos
            SET status = %s, pipeline_stage = NULL, analyzed_at = NULL, segment_count = NULL,
                cost_usd = NULL, asr_model = NULL, vlm_model = NULL, embedding_model = NULL,
                summary = NULL, summary_model = NULL
            WHERE id = %s
            """,
            (STATUS_PENDING, video_id),
        )


def delete_video(video_id: int) -> VideoRecord | None:
    """同樣把三張表的刪除放在同一個交易裡，理由見 reset_to_pending()。"""
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM videos WHERE id = %s", (video_id,)).fetchone()
        if row is None:
            return None
        segments.delete_for_video(conn, video_id)
        conn.execute("DELETE FROM ocr_events WHERE video_id = %s", (video_id,))
        conn.execute("DELETE FROM videos WHERE id = %s", (video_id,))
        return _row_to_record(row)


def update_video_status(video_id: int, status: str, pipeline_stage: str | None = None) -> None:
    with get_connection() as conn:
        conn.execute(
            "UPDATE videos SET status = %s, pipeline_stage = %s WHERE id = %s",
            (status, pipeline_stage, video_id),
        )


def mark_video_analyzed(
    video_id: int,
    segment_count: int,
    cost_usd: float,
    asr_model: str,
    vlm_model: str,
    embedding_model: str,
    pipeline_stage: str | None = None,
    summary: str | None = None,
    summary_model: str | None = None,
) -> None:
    """summary／summary_model 是自動摘要（Phase F）寫入用的可選欄位；不傳
    （None）就用 COALESCE 保留原本的值，不會覆蓋掉既有摘要（例如重新分析
    但這次自動摘要失敗的情況）。
    """
    analyzed_at = datetime.now().isoformat(timespec="seconds")
    with get_connection() as conn:
        conn.execute(
            """
            UPDATE videos
            SET status = %s, pipeline_stage = %s, analyzed_at = %s, segment_count = %s,
                cost_usd = %s, asr_model = %s, vlm_model = %s, embedding_model = %s,
                summary = COALESCE(%s, summary), summary_model = COALESCE(%s, summary_model)
            WHERE id = %s
            """,
            (
                STATUS_ANALYZED,
                pipeline_stage,
                analyzed_at,
                segment_count,
                cost_usd,
                asr_model,
                vlm_model,
                embedding_model,
                summary,
                summary_model,
                video_id,
            ),
        )


def _row_to_record(row: dict) -> VideoRecord:
    """後加的五個欄位不再需要 `if "x" in keys` 防呆，理由同
    `segments._row_to_segment()`：PostgreSQL 的 schema 一次定義齊全。
    """
    return VideoRecord(
        id=row["id"],
        title=row["title"],
        source=row["source"],
        source_url=row["source_url"],
        file_path=row["file_path"],
        duration_sec=row["duration_sec"],
        status=row["status"],
        pipeline_stage=row["pipeline_stage"],
        created_at=row["created_at"],
        analyzed_at=row["analyzed_at"],
        segment_count=row["segment_count"],
        cost_usd=row["cost_usd"],
        asr_model=row["asr_model"],
        vlm_model=row["vlm_model"],
        embedding_model=row["embedding_model"],
        summary=row["summary"],
        summary_model=row["summary_model"],
    )
