"""把既有 SQLite 資料庫的內容搬進 PostgreSQL，見 docs/14-postgresql-migration-plan.md P4。

一次性腳本，但寫成可重複執行（--truncate）方便驗證與重跑。

三個設計重點：

1. **保留原本的 id**。`docs/golden-set.csv` 直接引用 video_id，多輪對話的
   ConversationState 也存了 segment_id；id 一變，評測基準與既有對話全部對不上。
   schema 的 identity 欄位用 `GENERATED BY DEFAULT`（不是 `ALWAYS`）就是為了這件事，
   插入時可以直接指定 id。

2. **搬完必須修 sequence**。指定 id 插入不會推進 identity 的 sequence，不修的話
   下一筆 INSERT 會從 1 開始要號碼、直接撞主鍵。

3. **欄位對應用兩邊的 schema 推導，不寫死**。來源少了目標有的欄位、或多了目標
   沒有的欄位，都會在搬之前就報出來，而不是靜靜漏掉資料。目標端的 generated
   column（segments.content）會自動排除——那是資料庫自己算的，不能也不該插入。

用法：
    uv run python scripts/migrate_sqlite_to_pg.py --dry-run     # 只檢查對應關係
    uv run python scripts/migrate_sqlite_to_pg.py               # 目標非空會中止
    uv run python scripts/migrate_sqlite_to_pg.py --truncate    # 先清空目標再搬
"""
from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

from ai_video_search_web import db

# 搬移順序＝外鍵依賴順序：segments／ocr_events 的 video_id 指向 videos，
# videos 必須先進去。其餘三張表沒有外鍵，順序無所謂。
TABLES = ["videos", "segments", "ocr_events", "search_log", "jobs", "conversations"]


def _sqlite_columns(src: sqlite3.Connection, table: str) -> list[str]:
    return [row[1] for row in src.execute(f"PRAGMA table_info({table})")]


def _pg_columns(conn, table: str) -> list[str]:
    """目標表的可寫入欄位，依實體順序排列。

    排除 generated column：`segments.content` 由資料庫依 transcript／
    visual_description／ocr_text 自動算出，插入它會直接報錯。
    """
    rows = conn.execute(
        """
        SELECT column_name FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
          AND is_generated = 'NEVER'
        ORDER BY ordinal_position
        """,
        (table,),
    ).fetchall()
    return [r["column_name"] for r in rows]


def _plan_columns(src: sqlite3.Connection, conn, table: str) -> tuple[list[str], list[str]]:
    """回傳 (要搬的欄位, 警告訊息)。"""
    source = _sqlite_columns(src, table)
    target = _pg_columns(conn, table)
    shared = [c for c in target if c in source]

    warnings = []
    dropped = [c for c in source if c not in target]
    if dropped:
        warnings.append(f"來源有、目標沒有（資料會遺失）：{dropped}")
    missing = [c for c in target if c not in source]
    if missing:
        warnings.append(f"目標有、來源沒有（會填 NULL 或預設值）：{missing}")
    return shared, warnings


def _fix_sequence(conn, table: str) -> int | None:
    """把 identity 的 sequence 推到目前最大 id，避免下一筆 INSERT 撞主鍵。"""
    seq = conn.execute("SELECT pg_get_serial_sequence(%s, 'id') AS s", (table,)).fetchone()["s"]
    if seq is None:
        return None
    max_id = conn.execute(f"SELECT COALESCE(MAX(id), 0) AS m FROM {table}").fetchone()["m"]
    if max_id > 0:
        # is_called=true → 下一次取號是 max_id + 1
        conn.execute("SELECT setval(%s, %s, true)", (seq, max_id))
    else:
        # 空表：下一次取號要是 1，所以 is_called=false
        conn.execute("SELECT setval(%s, 1, false)", (seq,))
    return max_id


def _verify(src: sqlite3.Connection, conn) -> bool:
    """三道驗證，對應計畫 P4 的通過條件。"""
    print("\n=== 驗證 ===")
    ok = True

    print("\n1) 逐表筆數")
    for table in TABLES:
        a = src.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
        b = conn.execute(f"SELECT COUNT(*) AS c FROM {table}").fetchone()["c"]
        match = a == b
        ok &= match
        print(f"   {'✓' if match else '✗'} {table:<15} SQLite {a:>5}  PostgreSQL {b:>5}")

    print("\n2) 抽樣比對片段內容（前 3 支有片段的影片）")
    video_ids = [r[0] for r in src.execute(
        "SELECT DISTINCT video_id FROM segments ORDER BY video_id LIMIT 3")]
    for vid in video_ids:
        a = src.execute(
            "SELECT id, start_sec, end_sec, transcript, visual_description, ocr_text "
            "FROM segments WHERE video_id = ? ORDER BY id", (vid,)).fetchall()
        b = conn.execute(
            "SELECT id, start_sec, end_sec, transcript, visual_description, ocr_text "
            "FROM segments WHERE video_id = %s ORDER BY id", (vid,)).fetchall()
        same = len(a) == len(b) and all(
            tuple(ra) == (rb["id"], rb["start_sec"], rb["end_sec"],
                          rb["transcript"], rb["visual_description"], rb["ocr_text"])
            for ra, rb in zip(a, b))
        ok &= same
        print(f"   {'✓' if same else '✗'} video_id={vid:<4} {len(a)} 個片段逐欄位相符")

    print("\n3) embedding 逐位元組比對")
    checked = 0
    for col in ("transcript_embedding", "visual_embedding", "ocr_embedding"):
        a = src.execute(
            f"SELECT id, {col} FROM segments WHERE {col} IS NOT NULL ORDER BY id").fetchall()
        b = {r["id"]: r[col] for r in conn.execute(
            f"SELECT id, {col} FROM segments WHERE {col} IS NOT NULL")}
        same = len(a) == len(b) and all(bytes(b.get(sid, b"")) == blob for sid, blob in a)
        ok &= same
        checked += len(a)
        print(f"   {'✓' if same else '✗'} {col:<22} {len(a):>4} 筆完全相符")
    total_bytes = src.execute(
        "SELECT COALESCE(SUM(LENGTH(transcript_embedding)),0) + COALESCE(SUM(LENGTH(visual_embedding)),0)"
        " + COALESCE(SUM(LENGTH(ocr_embedding)),0) FROM segments").fetchone()[0]
    print(f"   合計 {checked} 個向量、{total_bytes:,} bytes")

    # ocr_events 的 embedding 是獨立欄位，一併比對
    a = src.execute("SELECT id, embedding FROM ocr_events WHERE embedding IS NOT NULL ORDER BY id").fetchall()
    b = {r["id"]: r["embedding"] for r in conn.execute(
        "SELECT id, embedding FROM ocr_events WHERE embedding IS NOT NULL")}
    same = len(a) == len(b) and all(bytes(b.get(oid, b"")) == blob for oid, blob in a)
    ok &= same
    print(f"   {'✓' if same else '✗'} ocr_events.embedding   {len(a):>4} 筆完全相符")

    return bool(ok)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=db.PROJECT_ROOT / "app.db",
                        help="來源 SQLite 檔案（預設專案根目錄的 app.db）")
    parser.add_argument("--truncate", action="store_true",
                        help="搬移前先清空目標資料表（否則目標非空就中止）")
    parser.add_argument("--dry-run", action="store_true",
                        help="只顯示欄位對應與筆數，不寫入任何資料")
    args = parser.parse_args()

    if not args.source.exists():
        print(f"找不到來源檔案：{args.source}", file=sys.stderr)
        return 1

    print(f"來源：{args.source}")
    print(f"目標：{db.DSN}\n")

    src = sqlite3.connect(f"file:{args.source}?mode=ro", uri=True)
    db.init_db()  # 冪等：確保 schema 是最新的，不用先手動跑過 app

    with db.get_connection() as conn:
        # --- 欄位對應 ---
        plans: dict[str, list[str]] = {}
        has_warning = False
        print("=== 欄位對應 ===")
        for table in TABLES:
            columns, warnings = _plan_columns(src, conn, table)
            plans[table] = columns
            n = src.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            print(f"  {table:<15} {len(columns):>2} 欄 · {n:>5} 筆")
            for w in warnings:
                has_warning = True
                print(f"      ⚠ {w}")
        if not has_warning:
            print("  （沒有欄位落差）")

        if args.dry_run:
            print("\n--dry-run：沒有寫入任何資料。")
            return 0

        # --- 目標非空的防呆 ---
        existing = {t: conn.execute(f"SELECT COUNT(*) AS c FROM {t}").fetchone()["c"] for t in TABLES}
        non_empty = {t: c for t, c in existing.items() if c}
        if non_empty:
            if not args.truncate:
                print(f"\n目標資料庫不是空的：{non_empty}", file=sys.stderr)
                print("重跑會撞主鍵。確定要覆蓋就加 --truncate。", file=sys.stderr)
                return 1
            print(f"\n--truncate：清空 {non_empty}")
            conn.execute(f"TRUNCATE {', '.join(TABLES)} RESTART IDENTITY CASCADE")

        # --- 搬移 ---
        # 整段在同一個交易裡（get_connection() 的 with 收尾才 commit），
        # 中途任何一張表失敗，前面搬好的會一起回滾，不會留下半套資料。
        print("\n=== 搬移 ===")
        for table in TABLES:
            columns = plans[table]
            rows = src.execute(f"SELECT {', '.join(columns)} FROM {table}").fetchall()
            if rows:
                placeholders = ", ".join(["%s"] * len(columns))
                conn.cursor().executemany(
                    f"INSERT INTO {table} ({', '.join(columns)}) VALUES ({placeholders})",
                    rows,
                )
            max_id = _fix_sequence(conn, table)
            print(f"  ✓ {table:<15} {len(rows):>5} 筆 · sequence → {max_id}")

        passed = _verify(src, conn)

    src.close()
    print("\n" + "=" * 52)
    print("✅ 全部通過" if passed else "❌ 驗證失敗（資料已寫入，請檢查後決定是否重跑）")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
